refactor and sonar fixes related changes
jhipster/jhipster-online pull request #434
Opened 2023-11-21 02:19 UTC by KaziNizamul

**Task Description:**
- refactored a few smelly code
- fixed a sonar issue

**Sonar Issue Id:**
-  https://sonarcloud.io/project/issues?resolved=false&id=jhipster_jhipster-online&open=AYqxq8ho8OMF9QyE-Uh6

**Affected files:**
- src/main/java/io/github/jhipster/online/domain/Jdl.java
- src/main/java/io/github/jhipster/online/domain/YoRC.java
- src/main/java/io/github/jhipster/online/service/EntityStatsService.java
- src/main/java/io/github/jhipster/online/service/GitService.java
- src/main/java/io/github/jhipster/online/service/SubGenEventService.java
- src/main/java/io/github/jhipster/online/service/util/SubGenEventStatisticsService.java
- src/main/java/io/github/jhipster/online/web/rest/GitResource.java

2023-11-21 14:33 UTC, KaziNizamul commented
Hello @DanielFran,

I tried to resolve some sonar fixes and refactoring changes for this repo.
Kindly have a look,
and let me know if any changes are required.

Thank you so much !

2023-11-22 18:55 UTC, KaziNizamul commented
Hi @DanielFran 
Kindly have a look and review the changes!

Thank you so much!

2023-11-24 12:41 UTC, KaziNizamul commented
Hi @DanielFran 
Kindly have a look and review the changes...
And kindlt let me know if any change is required...

2023-11-27 12:43 UTC, KaziNizamul commented
Hi @DanielFran / @deepu105 / @jdubois 
Requesting you to kindly have a look at the changes

And let me know if you want some more modification!  

I'm glad and grateful to contribute in this wonderful repository 😊!

2023-11-27 21:18 UTC, KaziNizamul commented
Hi @DanielFran ,

Kindly have a look at my changes,
if needed any changes please let know ! 

Thank you so much ! : )

2023-11-27 23:19 UTC, KaziNizamul commented
@SudharakaP @pascalgrimaud

2023-11-28 17:16 UTC, deepu105 requested changes

2023-11-28 17:16 UTC, deepu105 commented on src/main/java/io/github/jhipster/online/domain/Jdl.java
> +        if (isSameObject(o)) {
These are unnecessary changes IMO, just makes code more verbose and the methods are not even reused. Same for other methods added. Please revert back to original `equals` method

2023-11-28 17:16 UTC, deepu105 commented on src/main/java/io/github/jhipster/online/domain/Jdl.java
> +    // remove
why?

2023-11-28 17:16 UTC, deepu105 commented on src/main/java/io/github/jhipster/online/service/SubGenEventService.java
> +        SubGenEventStatisticsService subGenEventStatisticsService
i dont see the need to create another service here

2023-11-28 17:16 UTC, deepu105 commented on src/main/java/io/github/jhipster/online/service/util/SubGenEventStatisticsService.java
> +public class SubGenEventStatisticsService {
service should not be in utils package

2023-11-28 17:16 UTC, deepu105 commented on src/main/java/io/github/jhipster/online/service/SubGenEventService.java
> +        return subGenEventStatisticsService.getFieldCount(after, field, dbTemporalFunction);
if a seperate service is created better to call it directly from the controller instead of indirection here

2023-12-29 05:57 UTC, SudharakaP commented
@KaziNizamul : Thanks for the PR and sorry I wasn't able to look at these changes sooner. But could you please work on the changes that Deepu has suggested above and then we can work towards merging this soon.

2025-05-07 02:07 UTC, mraible commented
Closing due to lack of activity. Please reopen if you'd still like to fix things.

2025-05-07 02:07 UTC, closed without merging